#!/usr/bin/env bash
#
# Title: Kaweees's Ansible Playbook
# Description: A bash script to install Kaweee's Ansible playbook and run it.
# Author: Your Name

title() {
  local color='\033[1;37m'
  local nc='\033[0m'
  printf "\n${color}$1${nc}\n"
}

title "Greetings, $USER. Let's install Kaweees's Ansible Playbook."

# Install Ansible
sudo apt update -y && sudo apt upgrade -y
sudo apt install -y software-properties-common
sudo add-apt-repository --yes --update ppa:ansible/ansible
sudo apt install -y ansible git

# Execute Ansible playbook
ansible-pull -K -U https://github.com/Kaweees/ansible.git -t install local.yml
# Or run locally
# ansible-playbook -K local.yml -t install
