#!/usr/bin/env bash
#
# Title: Kaweees's Ansible Playbook
# Description: A bash script to install Kaweees's Ansible playbook and run it.
# Author: Miguel Villa Floran

title() {
  local color='\033[1;37m'
  local nc='\033[0m'
  printf "\n${color}$1${nc}\n"
}

title "Greetings, $USER. Let's install Kaweees's Ansible Playbook."

# Install Ansible
sudo apt update -y && sudo apt upgrade -y && sudo apt install -y software-properties-common ansible git cowsay

# Execute Ansible playbook remotely
# ansible-pull -K -U https://github.com/Kaweees/ansible.git local.yml --ask-become-pass --tags minimal-install

# Clone and execute Ansible playbook locally
git clone https://github.com/Kaweees/ansible.git ~/Documents/GitHub/Projects/ansible --recurse-submodules && cd ~/Documents/GitHub/Projects/ansible
ansible-playbook -K local.yml --ask-become-pass --tags minimal-install
