- name: Install required CLI utilities
  become: true
  package:
    name:
      - ansible
      - atool
      - autoconf
      - build-essential
      - clang-format
      - cmake
      - curl
      - dkms # Dynamic Kernel Module Support
      - ffmpeg
      - firmware-misc-nonfree
      - fzf
      - gcc
      - git
      - libnotify-bin
      - libtool
      - lm-sensors
      - make
      - man
      - network-manager # nmtui
      - network-manager-gnome # nm-connection-editor
      - picom
      - python3
      - python3-pip
      - pipx
      - ripgrep
      - stow
      - sudo
      - tree
      - unzip
      - wget
      - zsh
  tags:
    - minimal-install
    - install
    - core

- name: Install additional CLI utilities
  become: true
  package:
    name:
    - htop
    - neofetch
    - nmap
    - ranger
    - cowsay
  tags:
    - install
    - core
