- name: Install dotfiles
  ansible.builtin.git:
    repo: 'https://github.com/Kaweees/dotfiles'
    dest: "{{ dotfiles_location }}"
    recursive: true
    update: true
    accept_hostkey: true
  tags:
    - minimal-install
    - install
    - dotfiles
- name: Stow dotfiles
  shell: "cd {{ dotfiles_location }} && chmod +x ./setup.sh && bash ./setup.sh"
  tags:
    - minimal-install
    - install
    - dotfiles
