- name: Install dotfiles
  become: true
  ansible.builtin.shell:
    cmd: "git clone https://github.com/Kaweees/dotfiles.git {{ dotfiles_location }} --recurse-submodules && cd {{ dotfiles_location }} && python3 stowizer.py"
  tags:
    - minimal-install
    - install
    - dotfiles
