- name: Create keyring
  become: true
  ansible.builtin.shell:
    cmd: "sudo mkdir -p -m 755 /etc/apt/keyrings"
  tags:
    - minimal-install
    - install
    - git-cli
- name: Download GitHub CLI
  become: true
  ansible.builtin.shell:
    cmd: "wget -qO- https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo tee /etc/apt/keyrings/githubcli-archive-keyring.gpg > /dev/null"
  tags:
    - minimal-install
    - install
    - git-cli
- name: Change git-cli keyring to read and execute for everyone
  become: true
  ansible.builtin.shell:
    cmd: "chmod go+r /etc/apt/keyrings/githubcli-archive-keyring.gpg"
  tags:
    - minimal-install
    - install
    - git-cli
- name: git-cli
  become: true
  ansible.builtin.shell:
    cmd: 'echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null'
  tags:
    - minimal-install
    - install
    - git-cli
- name: Install git cli
  become: true
  ansible.builtin.shell:
    cmd: "sudo apt update && sudo apt install gh -y"
  tags:
    - minimal-install
    - install
    - git-cli

