---
- name: Install nvm version {{ nvm_version }}
  become: no
  ansible.builtin.shell: >
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v{{ nvm_version }}/install.sh | bash
  args:
    executable: /bin/bash
    chdir: "$HOME"
    creates: "$HOME/.nvm/versions/{{ nvm_version }}"
  when: nvm_version | regex_search('\\d.')
  tags:
    - install
    - nvm
    - node

- name: Source nvm to enable it
  become: no
  ansible.builtin.shell: >
    export NVM_DIR="$HOME/.nvm"
    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
    [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
  args:
    executable: /bin/bash
    chdir: "$HOME"
  tags:
    - install
    - nvm
    - node

- name: Install npm global packages
  become: true
  npm:
    name: "{{ item.name | default(item) }}"
    version: "{{ item.version | default(omit) }}"
    global: true
    state: "{{ item.state | default('present') }}"
  tags:
    - install
    - node
  with_items: "{{ nodejs_npm_global_packages }}"
