---
- name: Install nvm version {{ nvm_version }}
  become: no
  ansible.builtin.shell: >
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v{{ nvm_version }}/install.sh | bash
  args:
    executable: /bin/bash
    chdir: "$HOME"
    creates: "$HOME/.nvm/versions/{{ nvm_version }}"
  when: nvm_version | regex_search('\\d.')
  tags:
    - install
    - nvm
    - node

- name: Install Node.js version {{ nvm_node_version }}
  become: no
  ansible.builtin.shell: >
    . $HOME/.nvm/nvm.sh && nvm install {{ nvm_node_version }}
  args:
    executable: /bin/bash
    chdir: "$HOME"
    creates: "$HOME/.nvm/versions/{{ nvm_node_version }}"
  tags:
    - install
    - nvm
    - node
