- name: Set zsh as default shell
  shell: chsh -s $(which zsh)
  tags:
    - minimal-install
    - install
    - zsh

- name: Install gitstatus plugin
  ansible.builtin.git:
    repo: 'https://gitee.com/romkatv/gitstatus.git'
    dest: "~/gitstatus"
    recursive: true
    update: true
    accept_hostkey: true
  tags:
    - minimal-install
    - install
    - zsh

- name: Install onefetch
  shell: |
    sudo add-apt-repository ppa:o2sh/onefetch
    sudo apt-get update
    sudo apt-get install onefetch

- name: Install gpg
  shell: |
    sudo apt update
    sudo apt install -y gpg

- name: Install eza
  shell: |
    sudo mkdir -p /etc/apt/keyrings
    wget -qO- https://raw.githubusercontent.com/eza-community/eza/main/deb.asc | sudo gpg --dearmor -o /etc/apt/keyrings/gierens.gpg
    echo "deb [signed-by=/etc/apt/keyrings/gierens.gpg] http://deb.gierens.de stable main" | sudo tee /etc/apt/sources.list.d/gierens.list
    sudo chmod 644 /etc/apt/keyrings/gierens.gpg /etc/apt/sources.list.d/gierens.list
    sudo apt update

- name: Create usefull directories
  shell: |
    mkdir ~/Photos/screenshots
    mkdir ~/Documents/GitHub/Forks
    mkdir ~/Documents/Github/Projects
    mkdir ~/Documents/GitHub/Work
