# https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-githubs-form-schema
name: 🐛 Bug Report
description: Report a reproducible bug or regression to help us improve
title: "[BUG REPORT]: <title>"
labels: [bug]
assignees: []
body:
  - type: checkboxes
    attributes:
      label: Search before asking
      description: >
        🔍 Please search the [issues](https://github.com/Kaweees/ansible/issues) to see if a similar bug report already exists.
      options:
        - label: >
            I have searched the [project's issues](https://github.com/Kaweees/ansible/issues) and found no similar bug report.
          required: true
  - type: textarea
    attributes:
      label: System information
      description: 🖥️ The software and hardware used to produce the bug.
      placeholder: |
        - OS: Ubuntu 20.04
        - Ansible version: 2.10.5
        - GPU: Yes
    validations:
      required: false
  - type: textarea
    id: bug
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: To Reproduce
      description: "Steps to reproduce the behavior:"
      placeholder: "1. Go to '...'\n2. Click on '....'\n3. Scroll down to '....'\n4. See error"
    validations:
      required: true
  - type: textarea
    id: behavior
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: Additional information
      description: Additonal context about the bug, such as console output with error messages and/or screenshots of the bug.
      placeholder: "💡 ProTip! Include as much information as possible (screenshots, logs, tracebacks etc.) to receive the most helpful response."
    validations:
      required: false
