---
- name: Verify
  hosts: all
  become: true
  gather_facts: true

  tasks:
  - name: Verify Apache is serving web requests.
    ansible.builtin.uri:
      url: http://localhost/
      status_code: 200
